services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: manager_evaluation
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=backend.settings

volumes:
  postgres_data:
